apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/paprins/homelab.git
    targetRevision: main
    path: k3s/apps/authentik
  destination:
    name: in-cluster
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true