
---
apiVersion: v1
kind: Secret
metadata:
  name: skyhook
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: skyhook
  project: homelab
  type: helm
  url: https://skyhook-io.github.io/helm-charts
  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radar
  namespace: argocd
spec:
  project: homelab
  source:
    chart: radar
    repoURL: https://skyhook-io.github.io/helm-charts
    targetRevision: 1.5.14
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: radar.geeklabs.dev
              paths:
                - path: /
                  pathType: Prefix
        rbac:
          helm: true
          secrets: true
          viewRBAC: true
          portForward: true
  destination:
    name: in-cluster
    namespace: radar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true