apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radar
  namespace: argocd
spec:
  project: homelab
  source:
    chart: radar
    repoURL: https://skyhook-io.github.io/helm-charts
    targetRevision: 1.6.0
    helm:
      values: |
        ingress:
          enabled: true
        hosts:
          - host: radar.geeklabs.dev
            paths:
              - path: /
                pathType: Prefix
  destination:
    name: in-cluster
    namespace: radar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true