apiVersion: argoproj.io/v1alpha1                                                                                                                                      
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/paprins/homelab.git
    targetRevision: main
    path: k3s/apps/renovate
  destination:
    name: in-cluster
    namespace: renovate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true