apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/paprins/homelab.git
    targetRevision: main
    path: k3s/argocd/apps
    directory:
      recurse: true
      jsonnet: {}
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
