---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAA6whRmg6yrwc3kWhpvNxU/y3D+88WeGWd6obUdp5dQMcuLTqNZzBDgLwL/YWIy7/p7xf3lOavDlXobwQ8Si9XOD2gSzdXOtIPnDWLya0DQy80XrbNieEPDlrWF54msm2TP3f3j89aNHwV41pF/V2hg+nJjE3BjNW1GcftOU0QzjmiLvA+Pm43WAO+Ho3eza2Ku9Z0bbtuEZTLDzeao6F6TtHKF/WNWxoWpsbdNqqeGfZLOOfpzn8DFGw3F6G4xixc/fJ3mAxWU9h4fwjTL5XUO5gENjArbE5JXzXYSewR595Eapk6ndmc2Iu9jQux+7PKUANs5mAeKEkZI2Kua4Ohj1sRq4YvNxAskY+jO5EojE/qh55FPad3RaMQp03Xw+cTAsGFr7Omf8qxYsEqb4tDacnbur0ahvVGJwF9Ck5bO8GUsw/+188irSXV4M4xTwoDB5/wv7TQnLY0YEwOSg3qpktuu8Sigrq+mdJsqCG0lut95GpkvG4JHLCwLJnFaRlHiw0tgxuR1F2vtAS1bcMkIZFXALeY2eJohxhYwwb/E5IpnUgVeDzu5QiboUSAUlfruCrb9lkUItACUGlJDXnaMZaogA3mTO5OF3ZAxXW96aY/qhLB1X2Alm+MOhVIs+3X7ee+9nGd97E9rli3zAgnGPvDjHoFM5QYswailWIPmH14agFU1l03qJNNQM6iodAWwuOG2w8d7dd3O9EJ4ZCWMrGX9Vfk1/nLbr62DqQnQqu1+ytT9DDOJOmoknhYl7ajy1EM7bAYc2jRUC5AnFqEBoI24gwdCTvIM8m7XdGeyg==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
