---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAA6whRmg6yrwc3kWhpvNxU/y3D+88WeGWd6obUdp5dQMcuLTqNZzBDgLwL/YWIy7/p7xf3lOavDlXobwQ8Si9XOD2gSzdXOtIPnDWLya0DQy80XrbNieEPDlrWF54msm2TP3f3j89aNHwV41pF/V2hg+nJjE3BjNW1GcftOU0QzjmiLvA+Pm43WAO+Ho3eza2Ku9Z0bbtuEZTLDzeao6F6TtHKF/WNWxoWpsbdNqqeGfZLOOfpzn8DFGw3F6G4xixc/fJ3mAxWU9h4fwjTL5XUO5gENjArbE5JXzXYSewR595Eapk6ndmc2Iu9jQux+7PKUANs5mAeKEkZI2Kua4Ohj1sRq4YvNxAskY+jO5EojE/qh55FPad3RaMQp03Xw+cTAsGFr7Omf8qxYsEqb4tDacnbur0ahvVGJwF9Ck5bO8GUsw/+188irSXV4M4xTwoDB5/wv7TQnLY0YEwOSg3qpktuu8Sigrq+mdJsqCG0lut95GpkvG4JHLCwLJnFaRlHiw0tgxuR1F2vtAS1bcMkIZFXALeY2eJohxhYwwb/E5IpnUgVeDzu5QiboUSAUlfruCrb9lkUItACUGlJDXnaMZaogA3mTO5OF3ZAxXW96aY/qhLB1X2Alm+MOhVIs+3X7ee+9nGd97E9rli3zAgnGPvDjHoFM5QYswailWIPmH14agFU1l03qJNNQM6iodAWwuOG2w8d7dd3O9EJ4ZCWMrGX9Vfk1/nLbr62DqQnQqu1+ytT9DDOJOmoknhYl7ajy1EM7bAYc2jRUC5AnFqEBoI24gwdCTvIM8m7XdGeyg==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAxh5UQ+x43EL16wl/kKPDgG9ze4/Ng5JWtJwzs+7pxWK7cKA3hQ13gmB2KrAPTEtMoryqvjmBURdu2M11RMvbwoOlln8ZJdpu1sYcK2s1na0SClh2gAjBU8bftptwUbFDbPx88pV6l2PLPSXJOghK+NIEV3iiXj0Iejf5KTxgRAPUCjIy4U6qpBM31gIoledjXANph1GhxBTUNn12tRHGaF1ptnCb9LRa+brU50U4C+yxcMNLF+nBXQLwGthfGCdzsqJGR2h+J3Aj1wEFM06RgKTgQLSJPbbCWBtKo/2kxpR1kBZw7VK1EGODPpgT6V2zpF9vm1vJw05KZ3kkl0qQcsCHn2/+gbUH06jqI1KVvRRLC/dacVwheTxb97ndd7DRYVYV4rprdwzVJ/oTnEuRRrIZHqL96VMPJ+s4YOYpY6mPTzX1B+T20v/zv7N963WavpiFcrdg3QHSvkDSR81ZicfQ64KX35sgRw5tNBZSAYulPbHFWRIH7JIhA6S0L3UWDiOWoKSKSgdlX+a/8W0PFaBrpFi1wfn5uCYRdVggp5OQucuooME15PC0p60jmYhIKkcaaqoiFz1iV21pPNXKu+zNCowSzqUKa9PDqKxFucXJt2K/vvPw6rfct5zSqmgE4+skb7sJevP4UXxgO53Iu8dozaFxMLYfmfgYcKCpHlfoo9lDrpsLyzRnvm9tGMImAym8UEA+baQ0j8IOWH6qXLh7yVPxTipbdjFzmPMuWZzvh5Bycy4vmbtKKWBKne2w=
  template:
    metadata:
      name: authentik-postgres-credentials
      namespace: authentik