apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
  - name: longhorn
    version: 1.11.0
    repo: https://charts.longhorn.io
    releaseName: longhorn
    includeCRDs: true
    valuesFile: values.yaml
